Options:
  update-ticks: 20
  health-name: true
  health-tab: true

Worlds:
  world:
    title: '§5§lEND§f§lCRAFT'
    lines:
      - ''
      - '➢ §7§lRANK: §5'
      - '➢ §7§lCOINS : §f'
      - '➢ §7§lONLINE: §f%server_online%'
      - ''
      - '§5§lmc.anubissvk.online'
  world_nether:
    title: '§5§lEND§f§lCRAFT'
    lines:
      - ''
      - '➢ §7§lRANK: §5'
      - '➢ §7§lCOINS : §f'
      - '➢ §7§lONLINE: §f%server_online%'
      - ''
      - '§5§lmc.anubissvk.online'
  world_the_end:
    title: '§5§lEND§f§lCRAFT'
    lines:
      - ''
      - '➢ §7§lRANK: §5'
      - '➢ §7§lCOINS : §f'
      - '➢ §7§lONLINE: §f%server_online%'
      - ''
      - '§5§lmc.anubissvk.online'
